version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ia03
      MYSQL_DATABASE: ia03
      MYSQL_USER: ia03
      MYSQL_PASSWORD: ia03
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - usui-network

  springboot-app:
    container_name: ia03-be
    image: ia03-be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=ia03.phat.tros.vn
    networks:
      - usui-network
    depends_on:
      - mysql-db

  nginx-proxy-dev:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-dev
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ENABLE_IPV6=true
    privileged: true
    volumes:
      - vhostd:/etc/nginx/vhost.d
      - nginxcerts:/etc/nginx/certs:ro  # Thư mục chứa chứng chỉ SSL wildcard
      - nginxconf:/etc/nginx/conf.d
      - nginxlogs:/var/log/nginx
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - usui-network
    labels:
      - 'nginx_proxy=true'
      - com.github.nginx-proxy.nginx

volumes:
  mysql_data:
  vhostd:
  nginxcerts:
  nginxconf:
  nginxlogs:
  html:

networks:
  usui-network: