version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ia03
      MYSQL_DATABASE: ia03
      MYSQL_USER: ia03
      MYSQL_PASSWORD: ia03
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  springboot-app:
    container_name: ia03-be
    image: ia03-be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - ../selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - springboot-app

volumes:
  mysql_data:
